;;; -*- lexical-binding: t; -*-
(require 'init-modal)
(require 'init-theme)
(require 'init-completion)
(require 'init-lsp)
(require 'init-edit)
(require 'init-git)
(require 'init-project)
(require 'init-cc)
(require 'init-org)
(require 'init-citre)
(require 'init-sh)
