;;; -*- lexical-binding: t; -*-

(require 'init-utils)
(require 'init-modal)
(require 'init-theme)
(require 'init-completion)
(require 'init-lsp)
(require 'init-edit)
(require 'init-git)
(require 'init-project)
(require 'init-cc)
(require 'init-org)
(require 'init-citre)
(require 'init-sh)
(require 'init-rime)
(require 'init-debug)
(require 'init-minibuffer)
(require 'init-builtin)
(require 'init-window)
(require 'init-xterm)

(straight-use-package 'restart-emacs)
